#!/usr/bin/env php
<?php

require __DIR__.'/core/autoload_console.php';


/*
|----------------------------------------------
| Importing Console class namespace for usage
| Contains all modules and classes for cli usages
|----------------------------------------------
|
*/
use Console\Console;


/*
|----------------------------------------------
| Initializing the console app
|----------------------------------------------
| @param $argv - the command line arguments
|
*/

$console = new Console(
    new App\Core\Server(new App\Core\Modules\AppModules), $argv
);

/*
|----------------------------------------------
| Run the Console Application
|----------------------------------------------
|
| ALl command run on the cli will be handle and 
| response will be sent back to the terminal
|
*/

$console->run();
